// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7AVnyChH_AeiYA-l0dH7zxaQdMdRDjUs',
    appId: '1:877577363174:web:16969510f84e2731bfe527',
    messagingSenderId: '877577363174',
    projectId: 'school-mgmt-5a925',
    authDomain: 'school-mgmt-5a925.firebaseapp.com',
    storageBucket: 'school-mgmt-5a925.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLxCkfrXBzLyD20nPIxgFjSjN1rHMFye4',
    appId: '1:877577363174:android:c1fe089ec94bf573bfe527',
    messagingSenderId: '877577363174',
    projectId: 'school-mgmt-5a925',
    storageBucket: 'school-mgmt-5a925.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhUJyDrICI9yKogwVjl5PYVR-gLZkjfc0',
    appId: '1:877577363174:ios:94af77dd59854490bfe527',
    messagingSenderId: '877577363174',
    projectId: 'school-mgmt-5a925',
    storageBucket: 'school-mgmt-5a925.appspot.com',
    iosBundleId: 'com.example.schoolManagementApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhUJyDrICI9yKogwVjl5PYVR-gLZkjfc0',
    appId: '1:877577363174:ios:bb79824586c59f26bfe527',
    messagingSenderId: '877577363174',
    projectId: 'school-mgmt-5a925',
    storageBucket: 'school-mgmt-5a925.appspot.com',
    iosBundleId: 'com.example.schoolManagementApp.RunnerTests',
  );
}
